pull_request_rules:
  - name: automatically merge & label bots' PRs
    conditions:
      - author=scala-steward
      - author=developer47deg
      - status-success=test
    actions:
      merge:
        method: squash
      label:
        add: [auto-update]
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
